version: '3'

services:
  dev:
    image: node:latest
    volumes:
     - .:/usr/src/service/
     - ./nodemodules:/usr/src/service/node_modules
     # - nodemodules:/usr/src/service/node_modules
    working_dir: /usr/src/service
    entrypoint: ./docker-entrypoint.sh
    ports:
      - 3000:3000
      - 5000:5000
      - 8000:8000
